- apt: update_cache=yes

- name: Install list of packages Required for Jumpbox
  apt: pkg={{item}} state=installed
  with_items:
     - python-setuptools
     - git
     - aptitude
     - software-properties-common

# Install few dependences for ansible
- easy_install: name=pip #  puts it nicely in /usr/local/bin/pip
- pip: name=pip state=present extra_args='--upgrade' executable=/usr/local/bin/pip

#- pip: name=ansible state=present extra_args='--upgrade'
- pip: name=ansible state=present version=1.8.2
- pip: name=boto state=present

- pip: name=suds state=present

- pip: name=bigsuds state=present

#docker module only compat with version 1.1.0
#https://github.com/ansible/ansible/issues/10879
#- pip: name=docker-py state=present version=1.1.0 executable=/usr/local/bin/pip

- git: repo=git://github.com/cmutzel/aws-deployments.git
       dest=/home/"{{ansible_ssh_user}}"/aws-deployments
       accept_hostkey=True
  sudo: yes
  sudo_user: "{{ansible_ssh_user}}"

