---
- name: Create Vpc
  cloudformation:
    stack_name="{{ env_name }}-{{ inventory_hostname }}"
    state=present
    region="{{ region }}"
    template={{ install_path }}/roles/infra/files/vpc.json
  args:
    tags:
      Environment: "{{ env_name }}"
      InventoryHostname: "{{ inventory_hostname }}"
    template_parameters:
      cidrBlock: "{{ vpc_cidr }}"
  register: vpc_deploy_results

- name: persist vpc deploy results
  template: src='az-managers.j2' dest='~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/az-managers'

- copy: content="{{ vpc_deploy_results | to_yaml }}" dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml
